items:
- name: Конфигурация v1 (устарело)
  href: configuration-v1/index.md
- name: Конфигурация v2
  href: configuration-v2/index.md
- name: Аутентификация и авторизация узлов баз данных
  href: node-authorization.md
