items:
- name: Обзор конфигурации
  href: configuration-overview.md
- name: DSL конфигурации кластера
  href: dynamic-config-selectors.md
- name: Временная конфигурация
  href: dynamic-config-volatile-config.md
